services:
  poly-exporter:
    build:
      context: .
      dockerfile: ./polygon-mon/exporter-service/Dockerfile
    container_name: poly-exporter
    ports:
      - "8000:8000"
    restart: always

  poly-relay:
    build:
      context: .
      dockerfile: ./polygon-mon/relay-service/Dockerfile
    container_name: poly-relay
    ports:
      - "8001:8001"
      - "8006:8006"
    restart: always

  poly-producer:
    build:
      context: .
      dockerfile: ./polygon-mon/producer-service/Dockerfile
    container_name: poly-producer
    ports:
      - "8002:8002"
      - "8005:8005"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards/dashboard_provider.yml:/etc/grafana/provisioning/dashboards/dashboard_provider.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json_files

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  grafana-storage:
  prometheus-storage:
  loki-data:
  redis-data:
    driver: local
