{
 "title": "Poly Obs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "failed_poly_transactions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accepted Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "accepted_poly_transactions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Poly Base Fee (Gwei)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "polygon_market_base_fee_gwei", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Poly Prio Fee (Gwei) (p50)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polygon_market_priority_fee_gwei{percentile=\"50\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Poly Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "polygon_rpc_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "transaction_queue_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Local Nonce Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_nonce_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wallet Nonce Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wallet_nonce_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Polygon Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "polygon_node_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chain Request 95p Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"poly-relay\", severity=\"error\"} |= ``"
    }
   ]
  }
 ]
}